apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: fpp
spec:
  selector:
    app: minio
  clusterIP: None
  ports:
    - port: 9000
      targetPort: 9000
      name: minio
    - port: 9001
      targetPort: 9001
      name: minio-console

---
apiVersion: v1
kind: Service
metadata:
  name: minio-internal
  namespace: fpp
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      name: minio
    - port: 9001
      targetPort: 9001
      name: minio-console
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: fpp
spec:
  selector:
    app: minio
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
      nodePort: 30081
    - name: minio-console
      port: 9001
      targetPort: 9001
      nodePort: 30082
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: fpp
  labels:
    app: minio
spec:
  serviceName: minio-headless
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - --console-address
            - ":9001"
            - "http://minio-{0...3}.minio-headless.fpp.svc.cluster.local:9000/data"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - mountPath: /data
              name: minio-storage
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: minio-storage
      spec:
        storageClassName: my-storage-class
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: minio-deployment
#  namespace: fpp
#  labels:
#    app: minio
#spec:
#  selector:
#    matchLabels:
#      app: minio
#  template:
#    metadata:
#      labels:
#        app: minio
#    spec:
#      containers:
#        - name: minio
#          image: minio/minio
#          env:
#            - name: MINIO_ROOT_USER
#              value: minio
#            - name: MINIO_ROOT_PASSWORD
#              value: minio123
#          args:
#            - server
#            - --console-address
#            - ":9001"
#            - /data
#          ports:
#            - containerPort: 9000
#            - containerPort: 9001
#          volumeMounts:
#            - mountPath: /data
#              name: minio-storage
#      volumes:
#        - name: minio-storage
#          persistentVolumeClaim:
#            claimName: minio-pvc
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: minio-pvc
#  namespace: fpp
#spec:
#  storageClassName: my-storage-class
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
#
