kafka:
  topics:
    topic: fraud_topic
  server:
    bootstrap_servers: kafka-internal.fpp.svc.cluster.local:29092
  producer:
    retries: 3
    max_buffer: 10

storage:
  clickhouse:
    host: "clickhouse-internal.fpp.svc.cluster.local"
    port: 8123
    native_port: 9000       # native TCP port
    username: "fpp_user"
    password: ""
    jdbc_driver: "com.clickhouse.jdbc.ClickHouseDriver"
    native_driver: "com.clickhouse.spark.ClickHouseCatalog"
    database: "predictions"
    table:
      main_table: fraud_prediction
      monitor_table: model_monitor

  delta_lake:
    minio_endpoint: "http://minio-internal.fpp.svc.cluster.local:9000"
    minio_endpoint_sdk: "minio-internal.fpp.svc.cluster.local:9000"
    minio_access_key: "minio"
    minio_secret_key: "minio123"
    core_bucket: "deltalake"

model:
  model_1:
    id: model_1
  model_2:
    id: model_2
