apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processor
  namespace: fpp
  labels:
    app: stream-processor
spec:
  selector:
    matchLabels:
      app: stream-processor
  template:
    metadata:
      labels:
        app: stream-processor
    spec:
      containers:
        - name: stream-processor
          image: khoa2k4/project2:stream_processor
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ENV
              value: prod
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"