apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-processor
  namespace: fraud-prediction-platform
  labels:
    app: monitor-processor
spec:
  selector:
    matchLabels:
      app: monitor-processor
  template:
    metadata:
      labels:
        app: monitor-processor
    spec:
      containers:
        - name: monitor-processor
          image: khoa2k4/project2:monitor_processor
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: prod
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"